This Notebook is used to calculate the summary statistics for both clinical and RL-algorithms.

For RL algorithms: <br>
The results for experiments will be saved under "results/FOLDER_ID/AlgoSub_SEED".<br>
e.g., 'results/adult/G0_1'; G2P2C algorithm for adult subject 0 and seed 1.

In [3]:
import os 
import sys 
from decouple import config 
MAIN_PATH = r'C:\Users\jtrim\OneDrive\Documents\COMP4550\RL4T1D'
sys.path.insert(1, MAIN_PATH)
from visualiser.core import experiment_error_check
from visualiser.statistics import get_summary_stats, compare_algorithms

# First we quickly check and verify that the RL experiments have properly completed based on the 
# general template/guidelines used. You can customise additional parameters, check func "experiment_error_check".
experiment_error_check(cohort="child", algorithm='A2C', algoAbbreviation='A2C')
# experiment_error_check(cohort="child", algorithm='SAC', algoAbbreviation='SAC')

ModuleNotFoundError: No module named 'visualiser.statistics'

We calculate statistics (individual/cohort-levels) for identified clinical and RL metrics.
Target_metrics are time in normoglycemia (TIR), hypoglycemia, hyperglycemia, severe hypoglycemia, Severe hyperglycemia, LBGI (Low Blood Glucose Index), HBGI (High Blood Glucose Index), RI (Risk Index), Failure Rate, Reward.

In [2]:
# metrics and stats for RL agents and clinical, for a selected algorthm.
# Check parameters to get more information being calculated.
# Normal flow in the calculation: 
# For each subject, looking at 1500 simulations we calculate the metrics, you can get inter-quartile, mean, std etc.
# Using the mean for each metric we calculate cohort level metrics and statistics 
    
get_summary_stats(cohort="child", algo_type='rl', algorithm='A2C', algoAbbreviation='A2C', 
                  metric=['50%', '25%', '75%','mean', 'std'], 
                  verbose=False, show_res=True, sort=[False, 'hgbi'])

# get_summary_stats(cohort="adolescent", algo_type='clinical', algorithm='BBI', algoAbbreviation='BBI', 
#                   metric=['50%', '25%', '75%','mean', 'std'], 
#                   verbose=False, show_res=True, sort=[False, 'hgbi'])

Summary statistics for child cohort, A2C Algorithm

Summarised cohort statistics (mean):
    normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
id
0   60.21  6.98   8.53    6.53    17.75  7.37  12.79  20.16  129.35  63.80
1   40.54  0.10  22.41    0.01    36.95  0.25  18.63  18.88  235.65   0.00
2   45.28  0.20  16.27    0.03    38.22  0.51  22.13  22.65  227.19   1.73
3   56.86  6.18   8.45    6.37    22.14  6.77  14.55  21.32  110.21  68.87
4   48.71  1.33  21.43    0.60    27.92  1.72  16.34  18.06  235.06   4.60
5   39.81  0.34  16.98    0.15    42.73  0.76  24.49  25.25  215.09   5.47
6   53.31  0.16  21.98    0.04    24.51  0.49  13.80  14.28  250.13   0.20
7   58.31  3.54  10.81    1.98    25.35  3.18  18.78  21.96  200.49  41.80
8   55.82  8.18  13.99    4.79    17.22  5.19  11.21  16.40  187.57  38.60
9   60.97  6.56  10.43    6.56    15.48  5.95  10.28  16.23  166.55  38.73

Averaged cohort statistics:
      normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
50%   50.69  0.00  14.93    0.00    28.82  0.48  17.03  18.62  226.54  26.38
25%   39.24  0.00   8.52    0.00    10.42  0.00   9.54  13.67  185.49  26.38
75%   63.19  4.43  21.53    1.89    40.62  5.61  23.06  24.25  245.40  26.38
mean  51.98  3.36  15.13    2.71    26.83  3.22  16.30  19.52  195.73  26.38
std   17.13  6.26  10.20    6.00    18.84  4.65  10.00   7.70   76.19  26.38

      normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
50%   50.69  0.00  14.93    0.00    28.82  0.48  17.03  18.62  226.54  26.38
25%   39.24  0.00   8.52    0.00    10.42  0.00   9.54  13.67  185.49  26.38
75%   63.19  4.43  21.53    1.89    40.62  5.61  23.06  24.25  245.40  26.38
mean  51.98  3.36  15.13    2.71    26.83  3.22  16.30  19.52  195.73  26.38
std   17.13  6.26  10.20    6.00    18.84  4.65  10.00   7.70   76.19  26.38

In [4]:
get_summary_stats(cohort="child", algo_type='rl', algorithm='G2P2C', algoAbbreviation='G', 
                  metric=['50%', '25%', '75%','mean', 'std'], 
                  verbose=False, show_res=True, sort=[False, 'hgbi'])

Summary statistics for child cohort, G2P2C Algorithm

Summarised cohort statistics (mean):
    normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
id
0   50.41  1.68  18.54    0.32    29.05  2.68  20.24  22.91  235.37   7.53
1   58.91  0.11  25.97    0.00    15.00  0.61  10.41  11.02  260.33   0.00
2   55.95  0.19  15.46    0.02    28.37  0.65  16.60  17.25  244.68   0.07
3   59.55  1.47  24.16    0.44    14.38  2.34  10.86  13.21  256.26   4.67
4   72.01  1.99  21.65    0.20     4.14  2.27   7.25   9.52  270.15   1.27
5   61.24  0.73  16.14    0.07    21.82  1.51  14.38  15.89  254.30   0.80
6   73.67  0.83  17.50    0.06     7.94  1.45   8.32   9.78  269.66   0.40
7   59.71  0.63  11.45    0.06    28.15  1.51  20.98  22.48  232.87  10.00
8   78.02  0.77  15.46    0.04     5.70  1.34   6.77   8.12  272.40   0.60
9   66.58  2.45  15.57    0.24    15.16  2.33  12.25  14.58  259.16   1.40

Averaged cohort statistics:
      normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward  fail
50%   63.19  0.00  17.01    0.00    16.67  1.21  11.98  13.68  259.80  2.67
25%   56.94  0.00  13.19    0.00     7.29  0.56   8.07   9.62  247.12  2.67
75%   71.88  1.39  21.88    0.00    26.39  2.27  16.48  17.94  269.62  2.67
mean  63.60  1.09  18.19    0.15    16.97  1.67  12.81  14.48  255.52  2.67
std   11.55  2.23   6.74    0.75    11.21  1.68   5.81   6.09   20.95  2.67

      normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward  fail
50%   63.19  0.00  17.01    0.00    16.67  1.21  11.98  13.68  259.80  2.67
25%   56.94  0.00  13.19    0.00     7.29  0.56   8.07   9.62  247.12  2.67
75%   71.88  1.39  21.88    0.00    26.39  2.27  16.48  17.94  269.62  2.67
mean  63.60  1.09  18.19    0.15    16.97  1.67  12.81  14.48  255.52  2.67
std   11.55  2.23   6.74    0.75    11.21  1.68   5.81   6.09   20.95  2.67

In [2]:
# child
compare_algorithms(cohort="child", 
                   algo_types= ['clinical', 'clinical','rl', 'rl', 'rl', 'rl'],
                   algos=['BBI','BBHE','A2C','SAC','PPO', 'G2P2C'], 
                   abbreviations=['BBI','BBHE','A2C','SAC', 'P', 'G'])

Compare algorithm performance for the child cohort
       normo   hypo  hyper  S_hypo  S_hyper   lgbi   hgbi     ri  reward  \
Algo
BBI    67.21   5.13  13.92    2.65    11.09   5.42   9.03  14.44    0.00
BBHE   66.83   5.05  13.80    2.28    12.03   4.54   9.58  14.12    0.00
A2C    73.08   9.95   0.00   16.97     0.00  13.59   0.61  14.20    1.77
SAC    71.84  10.12   2.98   11.87     3.18  10.89   3.24  14.13   59.86
PPO    64.28   2.08  17.39    0.48    15.77   2.45  12.47  14.91  252.89
G2P2C  63.60   1.09  18.19    0.15    16.97   1.67  12.81  14.48  255.52

         fail
Algo
BBI     51.47
BBHE    39.18
A2C    100.00
SAC     93.75
PPO      5.38
G2P2C    2.67

,normo,hypo,hyper,S_hypo,S_hyper,lgbi,hgbi,ri,reward,fail
Algo,,,,,,,,,,
BBI,67.21,5.13,13.92,2.65,11.09,5.42,9.03,14.44,0.00,51.47
BBHE,66.83,5.05,13.80,2.28,12.03,4.54,9.58,14.12,0.00,39.18
A2C,73.08,9.95,0.00,16.97,0.00,13.59,0.61,14.20,1.77,100.00
SAC,71.84,10.12,2.98,11.87,3.18,10.89,3.24,14.13,59.86,93.75
PPO,64.28,2.08,17.39,0.48,15.77,2.45,12.47,14.91,252.89,5.38
G2P2C,63.60,1.09,18.19,0.15,16.97,1.67,12.81,14.48,255.52,2.67

In [2]:
# Adults
compare_algorithms(cohort="adult", 
                   algo_types= ['clinical', 'clinical','rl', 'rl', 'rl', 'rl'],
                   algos=['BBI','BBHE','A2C','SAC','PPO', 'G2P2C'], 
                   abbreviations=['BBI','BBHE','A2C','SAC', 'P', 'G'])

Compare algorithm performance for the adult cohort
       normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
Algo
BBI    71.02  0.64  24.43    0.06     3.85  1.33   7.02   8.35    0.00   0.39
BBHE   69.78  0.40  25.45    0.05     4.33  0.88   7.11   8.00    0.00   0.35
A2C    59.06  1.48  23.12    0.84    15.49  2.14  11.00  13.15  244.39   9.11
SAC    61.76  5.11  13.13    5.31    14.69  7.27  10.12  17.39  146.04  59.49
PPO    69.12  1.19  20.93    0.32     8.44  1.64   8.14   9.79  263.64   2.79
G2P2C  72.69  1.11  19.37    0.22     6.61  1.58   7.36   8.94  267.61   1.62

       normo  hypo  hyper  S_hypo  S_hyper  lgbi   hgbi     ri  reward   fail
Algo
BBI    71.02  0.64  24.43    0.06     3.85  1.33   7.02   8.35    0.00   0.39
BBHE   69.78  0.40  25.45    0.05     4.33  0.88   7.11   8.00    0.00   0.35
A2C    59.06  1.48  23.12    0.84    15.49  2.14  11.00  13.15  244.39   9.11
SAC    61.76  5.11  13.13    5.31    14.69  7.27  10.12  17.39  146.04  59.49
PPO    69.12  1.19  20.93    0.32     8.44  1.64   8.14   9.79  263.64   2.79
G2P2C  72.69  1.11  19.37    0.22     6.61  1.58   7.36   8.94  267.61   1.62